sudo: false
language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  global:
  - CXX=g++-4.8
node_js:
  - "4"
  - "6"
before_script:
  - redis-server /etc/redis/redis.conf --port 6379
install:
  - npm install
script:
  - npm run coverage
after_success:
  - npm run coveralls
notifications:
  email: ccharlieli@live.com
